[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "HPC Lab Docs"
authors = [{name = "HPC Lab", email = "hpcc@hcmut.edu.vn"}]
dynamic = ["version", "description"]
